apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-id-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowflake-id-generator
  template:
    metadata:
      labels:
        app: snowflake-id-generator
    spec:
      containers:
        - name: snowflake-id-generator
          image: snowflake-id-generator-1-0-0:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: snowflake-id-generator-service
spec:
  type: NodePort
  selector:
    app: snowflake-id-generator
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
