apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-id-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowflake-id-generator
  template:
    metadata:
      labels:
        app: snowflake-id-generator
    spec:
      containers:
        - name: snowflake-id-generator
          image: snowflake-id-generator-1-0-0:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: snowflake-id-generator-service
spec:
  type: NodePort
  selector:
    app: snowflake-id-generator
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
